const f=document.getElementById('brief-form');if(f){const q=new URLSearchParams(location.search);const prod={pack:'Упаковка',labels:'Этикетки и наклейки',print:'Полиграфия',books:'Книга / издательство',special:'Другое'};if(prod[q.get('product')])document.getElementById('product').value=prod[q.get('product')];if(q.get('audience')==='personal')document.getElementById('audience').value='Частное лицо';let msg='';f.addEventListener('submit',e=>{e.preventDefault();let v=id=>document.getElementById(id).value.trim();msg=['Запрос на расчёт · ДЕЛЬТА ПЛЮС','Заказчик: '+v('audience'),'Изделие: '+v('product'),'Тираж: '+(v('quantity')||'уточняется'),'Размер: '+(v('format')||'уточняется'),'Срок: '+(v('deadline')||'уточняется'),'Контакт: '+v('contact'),'Детали: '+(v('details')||'уточняются')].join('\n');document.getElementById('result-text').textContent=msg;document.getElementById('result').classList.add('show');location.href='mailto:deltaplus-upakovka@mail.ru?subject='+encodeURIComponent('Запрос на расчёт · '+v('product'))+'&body='+encodeURIComponent(msg)});document.getElementById('copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(msg);document.getElementById('copy-brief').textContent='Скопировано'}catch{document.getElementById('result-text').focus()}})}
const slider=document.querySelector('.visual-slider');if(slider){const slides=[...slider.querySelectorAll('.slide')],count=slider.querySelector('.slider-count'),toggle=slider.querySelector('.slider-toggle');let index=0,timer=null,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;function show(n){index=(n+slides.length)%slides.length;slides.forEach((s,i)=>{s.classList.toggle('is-active',i===index);s.setAttribute('aria-hidden',String(i!==index));s.querySelector('a').tabIndex=i===index?0:-1});count.textContent=String(index+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0')}function start(){clearInterval(timer);if(!paused)timer=setInterval(()=>show(index+1),6500)}function step(delta){show(index+delta);start()}slider.querySelector('.slider-prev').addEventListener('click',()=>step(-1));slider.querySelector('.slider-next').addEventListener('click',()=>step(1));toggle.addEventListener('click',()=>{paused=!paused;toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Возобновить смену кадров':'Остановить смену кадров');toggle.textContent=paused?'▶':'Ⅱ';start()});slider.addEventListener('mouseenter',()=>clearInterval(timer));slider.addEventListener('mouseleave',start);slider.addEventListener('focusin',()=>clearInterval(timer));slider.addEventListener('focusout',e=>{if(!slider.contains(e.relatedTarget))start()});slider.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});if(paused){toggle.setAttribute('aria-pressed','true');toggle.setAttribute('aria-label','Возобновить смену кадров');toggle.textContent='▶'}show(0);start()}

// Reveal content as it enters the viewport. Content remains visible if scripting or
// intersection observation is unavailable, and respects the visitor's motion setting.
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
  const revealSelector=['.section-head','.pricing-head','.card','.product-tile','.pricing-grid > *','.route','.step','.gallery-grid figure','.image-story-copy','.editorial-copy','.split > *','.footer-lead','.footer-details','.footer-map','.page-hero .wrap','.catalog-block','.form'];
  const reveals=[...document.querySelectorAll(revealSelector.join(','))];
  const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('motion-visible');observer.unobserve(entry.target)}}},{rootMargin:'0px 0px -35px 0px',threshold:0.08});
  reveals.forEach((el,i)=>{el.classList.add('motion-reveal');el.style.setProperty('--motion-delay',`${Math.min(i%4,3)*65}ms`);observer.observe(el)});
  const media=[...document.querySelectorAll('.image-story-media,.editorial-media,.photo-interlude')];
  let ticking=false;
  function updateMedia(){for(const el of media){const rect=el.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)continue;const progress=(innerHeight-rect.top)/(innerHeight+rect.height);el.style.setProperty('--motion-shift',`${Math.round((progress-.5)*32)}px`)}ticking=false}
  function onScroll(){if(!ticking){ticking=true;requestAnimationFrame(updateMedia)}}
  if(media.length){media.forEach(el=>el.classList.add('motion-media'));addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});onScroll()}
}
